#!/bin/bash -l
#SBATCH --job-name=MD-MACE_LAMMPS
#SBATCH --output=_scheduler-stdout.txt
#SBATCH --error=_scheduler-stderr.txt

#SBATCH --partition=normal
#SBATCH --account=your_cscs_account
#SBATCH --nodes=1
#SBATCH --gres=gpu:4
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=12
#SBATCH --hint=nomultithread
#SBATCH --time=12:00:00

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_PROC_BIND=spread
export OMP_PLACES=threads

cd $SLURM_SUBMIT_DIR


export INP=input.lammps
srun --mpi=pmix --environment=lammps-mace-kokkos \
     lmp -in $INP \
         -k on g 4 t $OMP_NUM_THREADS  \
         -sf kk \
         -pk kokkos newton on neigh half comm device cuda/aware off \
         -log dynamics_3.log


