#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --gpus-per-task=1
#SBATCH --account=your_account
#SBATCH --time=00:10:00
#SBATCH --uenv=lammps/20251210:v2
#SBATCH --view=kokkos
#SBATCH --partition=normal

export MPICH_GPU_SUPPORT_ENABLED=1
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
ulimit -s unlimited

srun bash -c "
source /path_to_your/my-venv-lammps-mace/bin/activate
lmp -k on g 1 -sf kk -pk kokkos gpu/aware on newton on neigh half -in input.lammps -log my_log.log
"
