#!/bin/bash -l
#SBATCH --job-name=mace-train-test
#SBATCH --output=mace_train_%j.out
#SBATCH --error=mace_train_%j.err
#SBATCH --partition=normal
#SBATCH --account=lp83
#SBATCH --nodes=1
#SBATCH --gres=gpu:4
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=72
#SBATCH --time=0:30:00
#SBATCH --hint=nomultithread

# PyTorch DDP env
export MASTER_ADDR=$(hostname)
export MASTER_PORT=29400
export WORLD_SIZE=$SLURM_NTASKS
export TORCH_NCCL_ASYNC_ERROR_HANDLING=1
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

# Optional NCCL tuning for CSCS
export NCCL_NET="AWS Libfabric"
export NCCL_NET_GDR_LEVEL=PHB
export NCCL_CROSS_NIC=1
export FI_CXI_DISABLE_HOST_REGISTER=1
export FI_MR_CACHE_MONITOR=userfaultfd
export FI_CXI_DEFAULT_CQ_SIZE=131072
export FI_CXI_DEFAULT_TX_SIZE=32768
export FI_CXI_RX_MATCH_MODE=software

cd "$SLURM_SUBMIT_DIR"

srun --cpus-per-task=$SLURM_CPUS_PER_TASK --environment=lammps-mace-kokkos python3 std_max.py > output_std.dat
wait

awk {'print $3'} model_devi.log > model_devi.out

